


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "warehouse";


ALTER SCHEMA "warehouse" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "warehouse"."dealer_documents" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "dealer_code" character varying(255) NOT NULL,
    "document_type" character varying(50) NOT NULL,
    "document_number" character varying(255) NOT NULL,
    "document_data" "jsonb" NOT NULL,
    "file_url" "text",
    "generated_at" timestamp with time zone DEFAULT "now"(),
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "dealer_documents_document_type_check" CHECK ((("document_type")::"text" = ANY ((ARRAY['quotation'::character varying, 'invoice'::character varying, 'receipt'::character varying, 'delivery_note'::character varying])::"text"[])))
);


ALTER TABLE "warehouse"."dealer_documents" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "warehouse"."showroom_documents" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "showroom_code" character varying(255) NOT NULL,
    "document_type" character varying(50) NOT NULL,
    "document_number" character varying(255) NOT NULL,
    "document_data" "jsonb" NOT NULL,
    "file_url" "text",
    "generated_at" timestamp with time zone DEFAULT "now"(),
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "showroom_documents_document_type_check" CHECK ((("document_type")::"text" = ANY ((ARRAY['quotation'::character varying, 'invoice'::character varying, 'receipt'::character varying, 'delivery_note'::character varying])::"text"[])))
);


ALTER TABLE "warehouse"."showroom_documents" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "warehouse"."vehicle_inventory" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "model_code" "text" NOT NULL,
    "engine_number" "text" NOT NULL,
    "chassis_number" "text" NOT NULL,
    "color" "text" NOT NULL,
    "yom" "text" NOT NULL,
    "version" "text" NOT NULL,
    "price" numeric(12,2) NOT NULL,
    "status" "text" DEFAULT 'AVAILABLE'::"text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "issued_to" "text" DEFAULT 'none'::"text" NOT NULL,
    "issued_at" timestamp with time zone,
    "requested_by" "text",
    "requested_at" timestamp with time zone,
    "request_reference" "text",
    CONSTRAINT "vehicle_inventory_status_check" CHECK (("status" = ANY (ARRAY['AVAILABLE'::"text", 'REQUESTED'::"text", 'ISSUED'::"text", 'RESERVED'::"text", 'DAMAGED'::"text", 'TRANSFERRED'::"text"])))
);


ALTER TABLE "warehouse"."vehicle_inventory" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "warehouse"."vehicle_model_codes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "model_code" "text" NOT NULL,
    "model_name" "text" NOT NULL,
    "price" "text" NOT NULL,
    "arrived_quantity" bigint DEFAULT 0 NOT NULL,
    "warehouse_quantity" bigint DEFAULT '0'::bigint NOT NULL
);


ALTER TABLE "warehouse"."vehicle_model_codes" OWNER TO "postgres";


ALTER TABLE "warehouse"."vehicle_model_codes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "warehouse"."vehicle_model_codes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "warehouse"."vehicle_spare_codes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "model_code" "text" NOT NULL,
    "spare_code" "text" NOT NULL,
    "spare_name" "text" NOT NULL,
    "price" "text",
    "arrived_quantity" bigint NOT NULL,
    "warehouse_quantity" bigint DEFAULT '0'::bigint NOT NULL
);


ALTER TABLE "warehouse"."vehicle_spare_codes" OWNER TO "postgres";


ALTER TABLE "warehouse"."vehicle_spare_codes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "warehouse"."vehicle_spare_codes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "warehouse"."vehicle_spare_inventory" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "model_code" "text" NOT NULL,
    "spare_code" "text" NOT NULL,
    "serial_number" "text" NOT NULL,
    "issued_to" "text" DEFAULT 'none'::"text" NOT NULL,
    "issued_at" timestamp with time zone,
    "price" "text",
    "status" "text" DEFAULT 'AVAILABLE'::"text" NOT NULL,
    "requested_by" "text",
    "requested_at" timestamp with time zone,
    "request_reference" "text",
    CONSTRAINT "vehicle_spare_inventory_status_check" CHECK (("status" = ANY (ARRAY['AVAILABLE'::"text", 'REQUESTED'::"text", 'ISSUED'::"text", 'RESERVED'::"text", 'DAMAGED'::"text", 'TRANSFERRED'::"text"])))
);


ALTER TABLE "warehouse"."vehicle_spare_inventory" OWNER TO "postgres";


ALTER TABLE "warehouse"."vehicle_spare_inventory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "warehouse"."vehicle_spare_inventory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "warehouse"."dealer_documents"
    ADD CONSTRAINT "dealer_documents_document_number_key" UNIQUE ("document_number");



ALTER TABLE ONLY "warehouse"."dealer_documents"
    ADD CONSTRAINT "dealer_documents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "warehouse"."showroom_documents"
    ADD CONSTRAINT "showroom_documents_document_number_key" UNIQUE ("document_number");



ALTER TABLE ONLY "warehouse"."showroom_documents"
    ADD CONSTRAINT "showroom_documents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "warehouse"."vehicle_inventory"
    ADD CONSTRAINT "vehicle_inventory_chassis_number_key" UNIQUE ("chassis_number");



ALTER TABLE ONLY "warehouse"."vehicle_inventory"
    ADD CONSTRAINT "vehicle_inventory_engine_number_key" UNIQUE ("engine_number");



ALTER TABLE ONLY "warehouse"."vehicle_inventory"
    ADD CONSTRAINT "vehicle_inventory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "warehouse"."vehicle_spare_codes"
    ADD CONSTRAINT "vehicle_spare_codes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "warehouse"."vehicle_spare_codes"
    ADD CONSTRAINT "vehicle_spare_codes_spare_code_key" UNIQUE ("spare_code");



ALTER TABLE ONLY "warehouse"."vehicle_spare_inventory"
    ADD CONSTRAINT "vehicle_spare_inventory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "warehouse"."vehicle_spare_inventory"
    ADD CONSTRAINT "vehicle_spare_inventory_serial_no_key" UNIQUE ("serial_number");



ALTER TABLE ONLY "warehouse"."vehicle_model_codes"
    ADD CONSTRAINT "vehiclemodelcodes_model_code_key" UNIQUE ("model_code");



ALTER TABLE ONLY "warehouse"."vehicle_model_codes"
    ADD CONSTRAINT "vehiclemodelcodes_model_name_key" UNIQUE ("model_name");



ALTER TABLE ONLY "warehouse"."vehicle_model_codes"
    ADD CONSTRAINT "vehiclemodelcodes_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_chassis_number" ON "warehouse"."vehicle_inventory" USING "btree" ("chassis_number");



CREATE INDEX "idx_dealer_documents_dealer_code" ON "warehouse"."dealer_documents" USING "btree" ("dealer_code");



CREATE INDEX "idx_dealer_documents_document_number" ON "warehouse"."dealer_documents" USING "btree" ("document_number");



CREATE INDEX "idx_dealer_documents_document_type" ON "warehouse"."dealer_documents" USING "btree" ("document_type");



CREATE INDEX "idx_dealer_documents_generated_at" ON "warehouse"."dealer_documents" USING "btree" ("generated_at");



CREATE INDEX "idx_engine_number" ON "warehouse"."vehicle_inventory" USING "btree" ("engine_number");



CREATE INDEX "idx_showroom_documents_document_number" ON "warehouse"."showroom_documents" USING "btree" ("document_number");



CREATE INDEX "idx_showroom_documents_document_type" ON "warehouse"."showroom_documents" USING "btree" ("document_type");



CREATE INDEX "idx_showroom_documents_generated_at" ON "warehouse"."showroom_documents" USING "btree" ("generated_at");



CREATE INDEX "idx_showroom_documents_showroom_code" ON "warehouse"."showroom_documents" USING "btree" ("showroom_code");



CREATE INDEX "idx_spare_inventory_code" ON "warehouse"."vehicle_spare_inventory" USING "btree" ("spare_code");



CREATE INDEX "idx_spare_request_reference" ON "warehouse"."vehicle_spare_inventory" USING "btree" ("request_reference");



CREATE INDEX "idx_spare_requested_by" ON "warehouse"."vehicle_spare_inventory" USING "btree" ("requested_by");



CREATE INDEX "idx_spare_serial" ON "warehouse"."vehicle_spare_inventory" USING "btree" ("serial_number");



CREATE INDEX "idx_spare_status_requested" ON "warehouse"."vehicle_spare_inventory" USING "btree" ("status") WHERE ("status" = 'REQUESTED'::"text");



CREATE INDEX "idx_vehicle_model_code" ON "warehouse"."vehicle_inventory" USING "btree" ("model_code");



CREATE INDEX "idx_vehicle_request_reference" ON "warehouse"."vehicle_inventory" USING "btree" ("request_reference");



CREATE INDEX "idx_vehicle_requested_by" ON "warehouse"."vehicle_inventory" USING "btree" ("requested_by");



CREATE INDEX "idx_vehicle_status_requested" ON "warehouse"."vehicle_inventory" USING "btree" ("status") WHERE ("status" = 'REQUESTED'::"text");



ALTER TABLE ONLY "warehouse"."vehicle_inventory"
    ADD CONSTRAINT "vehicle_inventory_model_code_fkey" FOREIGN KEY ("model_code") REFERENCES "warehouse"."vehicle_model_codes"("model_code") ON DELETE CASCADE;



ALTER TABLE ONLY "warehouse"."vehicle_spare_inventory"
    ADD CONSTRAINT "vehicle_spare_inventory_spare_code_fkey" FOREIGN KEY ("spare_code") REFERENCES "warehouse"."vehicle_spare_codes"("spare_code");



CREATE POLICY "admin_all_dealer_documents" ON "warehouse"."dealer_documents" USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."jwt"() ->> 'role'::"text") = 'admin'::"text"))) WITH CHECK ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."jwt"() ->> 'role'::"text") = 'admin'::"text")));



CREATE POLICY "admin_all_showroom_documents" ON "warehouse"."showroom_documents" USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."jwt"() ->> 'role'::"text") = 'admin'::"text"))) WITH CHECK ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."jwt"() ->> 'role'::"text") = 'admin'::"text")));



ALTER TABLE "warehouse"."dealer_documents" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "dealer_view_own_documents" ON "warehouse"."dealer_documents" FOR SELECT USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."jwt"() ->> 'role'::"text") = 'dealer'::"text") AND (("dealer_code")::"text" = ("auth"."jwt"() ->> 'code'::"text"))));



CREATE POLICY "service_role_all_dealer_documents" ON "warehouse"."dealer_documents" USING (("auth"."role"() = 'service_role'::"text")) WITH CHECK (("auth"."role"() = 'service_role'::"text"));



CREATE POLICY "service_role_all_showroom_documents" ON "warehouse"."showroom_documents" USING (("auth"."role"() = 'service_role'::"text")) WITH CHECK (("auth"."role"() = 'service_role'::"text"));



ALTER TABLE "warehouse"."showroom_documents" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "showroom_view_own_documents" ON "warehouse"."showroom_documents" FOR SELECT USING ((("auth"."role"() = 'authenticated'::"text") AND (("auth"."jwt"() ->> 'role'::"text") = 'showroom'::"text") AND (("showroom_code")::"text" = ("auth"."jwt"() ->> 'code'::"text"))));



ALTER TABLE "warehouse"."vehicle_inventory" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "vehicle_inventory_delete" ON "warehouse"."vehicle_inventory" FOR DELETE TO "authenticated", "anon", "service_role" USING ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



CREATE POLICY "vehicle_inventory_insert" ON "warehouse"."vehicle_inventory" FOR INSERT TO "authenticated", "anon", "service_role" WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



CREATE POLICY "vehicle_inventory_select" ON "warehouse"."vehicle_inventory" FOR SELECT TO "authenticated", "anon", "service_role" USING (true);



CREATE POLICY "vehicle_inventory_update" ON "warehouse"."vehicle_inventory" FOR UPDATE TO "authenticated", "anon", "service_role" USING ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text"))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



ALTER TABLE "warehouse"."vehicle_model_codes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "vehicle_model_codes_delete" ON "warehouse"."vehicle_model_codes" FOR DELETE TO "authenticated", "anon", "service_role" USING ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



CREATE POLICY "vehicle_model_codes_insert" ON "warehouse"."vehicle_model_codes" FOR INSERT TO "authenticated", "anon", "service_role" WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



CREATE POLICY "vehicle_model_codes_select" ON "warehouse"."vehicle_model_codes" FOR SELECT TO "authenticated", "anon", "service_role" USING (true);



CREATE POLICY "vehicle_model_codes_update" ON "warehouse"."vehicle_model_codes" FOR UPDATE TO "authenticated", "anon", "service_role" USING ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text"))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



ALTER TABLE "warehouse"."vehicle_spare_codes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "vehicle_spare_codes_delete" ON "warehouse"."vehicle_spare_codes" FOR DELETE TO "authenticated", "anon", "service_role" USING ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



CREATE POLICY "vehicle_spare_codes_insert" ON "warehouse"."vehicle_spare_codes" FOR INSERT TO "authenticated", "anon", "service_role" WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



CREATE POLICY "vehicle_spare_codes_select" ON "warehouse"."vehicle_spare_codes" FOR SELECT TO "authenticated", "anon", "service_role" USING (true);



CREATE POLICY "vehicle_spare_codes_update" ON "warehouse"."vehicle_spare_codes" FOR UPDATE TO "authenticated", "anon", "service_role" USING ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text"))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



ALTER TABLE "warehouse"."vehicle_spare_inventory" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "vehicle_spare_inventory_delete" ON "warehouse"."vehicle_spare_inventory" FOR DELETE TO "authenticated", "anon", "service_role" USING ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



CREATE POLICY "vehicle_spare_inventory_insert" ON "warehouse"."vehicle_spare_inventory" FOR INSERT TO "authenticated", "anon", "service_role" WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



CREATE POLICY "vehicle_spare_inventory_select" ON "warehouse"."vehicle_spare_inventory" FOR SELECT TO "authenticated", "anon", "service_role" USING (true);



CREATE POLICY "vehicle_spare_inventory_update" ON "warehouse"."vehicle_spare_inventory" FOR UPDATE TO "authenticated", "anon", "service_role" USING ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text"))) WITH CHECK ((("auth"."role"() = 'service_role'::"text") OR ("auth"."role"() = 'authenticated'::"text")));



GRANT USAGE ON SCHEMA "warehouse" TO "anon";
GRANT USAGE ON SCHEMA "warehouse" TO "authenticated";
GRANT USAGE ON SCHEMA "warehouse" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."dealer_documents" TO "anon";
GRANT ALL ON TABLE "warehouse"."dealer_documents" TO "authenticated";
GRANT ALL ON TABLE "warehouse"."dealer_documents" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."showroom_documents" TO "anon";
GRANT ALL ON TABLE "warehouse"."showroom_documents" TO "authenticated";
GRANT ALL ON TABLE "warehouse"."showroom_documents" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_inventory" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_inventory" TO "authenticated";
GRANT ALL ON TABLE "warehouse"."vehicle_inventory" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_model_codes" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_model_codes" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_model_codes" TO "service_role";



GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_model_codes_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_model_codes_id_seq" TO "authenticated";
GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_model_codes_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_spare_codes" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_spare_codes" TO "authenticated";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_spare_codes" TO "service_role";



GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_spare_codes_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_spare_codes_id_seq" TO "authenticated";
GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_spare_codes_id_seq" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_spare_inventory" TO "anon";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "warehouse"."vehicle_spare_inventory" TO "authenticated";
GRANT ALL ON TABLE "warehouse"."vehicle_spare_inventory" TO "service_role";



GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_spare_inventory_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_spare_inventory_id_seq" TO "authenticated";
GRANT SELECT,USAGE ON SEQUENCE "warehouse"."vehicle_spare_inventory_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "warehouse" GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "warehouse" GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "warehouse" GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO "service_role";




